// Parity check: the JS engine (Figma plugin) must produce the same audit and the same
// tokens.css / manifest as tokenkit.py. Usage: node tests/parity.js <python-out-dir> <kind> <input> [changes.json]
// <python-out-dir> must contain audit.json, tokens.css and tokens.manifest.json from tokenkit.py.
const fs = require("fs");
const path = require("path");
const TK = require("../skills/token-push-figma/figma-plugin/engine.js");
const [dir, kind, input, changesFile] = process.argv.slice(2);
const raw = fs.readFileSync(input, "utf8");
const file = path.basename(input);
const model = kind === "css" ? TK.ingestCss(raw, null, file) : TK.ingestFigma(JSON.parse(raw), file);
const audit = TK.audit(model);
const gen = TK.generate(model, { changes: changesFile ? JSON.parse(fs.readFileSync(changesFile, "utf8")) : [] });

const py = JSON.parse(fs.readFileSync(path.join(dir, "audit.json"), "utf8"));
const pyCss = fs.readFileSync(path.join(dir, "tokens.css"), "utf8");
const pyMan = JSON.parse(fs.readFileSync(path.join(dir, "tokens.manifest.json"), "utf8"));
let fails = 0;
const eq = (label, a, b) => {
  const sa = JSON.stringify(a), sb = JSON.stringify(b);
  if (sa !== sb) { fails++; console.log("DIFF " + label + "\n  js: " + sa.slice(0, 400) + "\n  py: " + sb.slice(0, 400)); }
};
const num = (o) => JSON.parse(JSON.stringify(o), (k, v) => (typeof v === "number" ? Math.round(v * 1000) / 1000 : v));
eq("scores", audit.summary.scores, py.summary.scores);
eq("findings", num(audit.findings), num(py.findings));
eq("ai", num(audit.ai), num(py.ai));
eq("contrast", num(audit.contrast), num(py.contrast));
eq("suggestions", audit.suggestions, py.suggestions);
const strip = (s) => s.split("\n").filter((l) => !l.includes("Generated by")).join("\n");
eq("css", strip(gen.css), strip(pyCss));
const manNorm = (m) => num({ collections: m.collections, tokens: m.tokens, changes: m.changes });
eq("manifest", manNorm(gen.manifest), manNorm(pyMan));
console.log(fails ? fails + " differences" : "parity ok");
process.exit(fails ? 1 : 0);
