#!/usr/bin/env bash
# End-to-end tests for token-foundry. Needs python3 (3.8+) and node (18+).
# Usage: bash tests/run-tests.sh
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
K="$ROOT/skills/token-audit/scripts/tokenkit.py"
FX="$ROOT/tests/fixtures"
W="$(mktemp -d)"
trap 'rm -rf "$W"' EXIT
pass=0; fail=0
ok()   { echo "  ok   $1"; pass=$((pass+1)); }
bad()  { echo "  FAIL $1"; fail=$((fail+1)); }
same_css() { diff <(grep -v 'Generated by' "$1") <(grep -v 'Generated by' "$2") >/dev/null; }
no_changes() { grep -q '"changes": {}' "$1"; }

echo "1. Figma export -> audit -> generate"
python3 "$K" ingest "$FX/figma-variables-demo.json" -o "$W/f/model.json" 2>/dev/null >/dev/null
python3 "$K" audit "$W/f/model.json" -o "$W/f" 2>/dev/null >/dev/null
python3 "$K" generate "$W/f/model.json" -o "$W/f" 2>/dev/null >/dev/null
[ -s "$W/f/tokens.css" ] && [ -s "$W/f/tokens.manifest.json" ] && ok "outputs written" || bad "outputs written"
python3 - "$W/f" <<'EOF' && ok "semantic tokens only reference primitives" || bad "semantic tokens only reference primitives"
import json, sys
m = json.load(open(sys.argv[1] + "/tokens.manifest.json"))
tiers = {c["name"]: c["tier"] for c in m["collections"]}
lit = [t["name"] for t in m["tokens"] if tiers[t["collection"]] != "primitive" and t["type"] == "COLOR"
       and any("value" in v for v in t["values"].values())]
sys.exit(1 if lit else 0)
EOF
grep -q '4.48<4.5' "$W/f/audit.md" && ok "contrast failure detected (text/muted 4.48)" || bad "contrast failure detected"
grep -q 'surface/hover == Mapped::surface/disabled' "$W/f/audit.md" && ok "identical states detected" || bad "identical states detected"
grep -q -- '--color-grey-650: #717171' "$W/f/tokens.css" && ok "missing primitive placed in ramp (grey/650)" || bad "missing primitive placed in ramp"
grep -q '"figmaId": "VariableID:' "$W/f/tokens.manifest.json" && ok "Figma IDs kept in manifest" || bad "Figma IDs kept in manifest"
! grep -q 'VariableID' "$W/f/tokens.css" && ok "CSS has no Figma IDs" || bad "CSS has no Figma IDs"

echo "2. Round trips and idempotency"
python3 "$K" ingest "$W/f/tokens.css" --manifest "$W/f/tokens.manifest.json" -o "$W/r/model.json" 2>/dev/null >/dev/null
python3 "$K" generate "$W/r/model.json" -o "$W/r" 2>"$W/r/log" >/dev/null
no_changes "$W/r/log" && ok "second generate: 0 changes" || bad "second generate: 0 changes"
same_css "$W/f/tokens.css" "$W/r/tokens.css" && ok "CSS -> CSS identical" || bad "CSS -> CSS identical"
python3 "$K" ingest "$W/f/tokens.manifest.json" -o "$W/m/model.json" 2>/dev/null >/dev/null
python3 "$K" generate "$W/m/model.json" -o "$W/m" 2>/dev/null >/dev/null
same_css "$W/f/tokens.css" "$W/m/tokens.css" && ok "manifest -> CSS identical" || bad "manifest -> CSS identical"
python3 "$K" ingest "$FX/figma-rest-demo.json" -o "$W/rest/model.json" 2>/dev/null >/dev/null
python3 "$K" generate "$W/rest/model.json" -o "$W/rest" 2>/dev/null >/dev/null
same_css "$W/f/tokens.css" "$W/rest/tokens.css" && ok "Figma REST format = plugin format" || bad "Figma REST format = plugin format"

echo "3. Plain CSS input"
python3 "$K" ingest "$FX/tokens-demo.css" -o "$W/c/model.json" 2>/dev/null >/dev/null
python3 "$K" audit "$W/c/model.json" -o "$W/c" 2>/dev/null >/dev/null
python3 "$K" generate "$W/c/model.json" -o "$W/c" 2>/dev/null >/dev/null
grep -q '\[data-theme="dark"\]' "$W/c/tokens.css" && ok "dark theme selector kept" || bad "dark theme selector kept"
grep -q '@media (max-width: 600px)' "$W/c/tokens.css" && ok "media query kept" || bad "media query kept"
grep -q -- '--shadow-md: 0 1px 3px' "$W/c/tokens.css" && ok "shadow kept literal" || bad "shadow kept literal"
grep -q 'button/primary/text on button/primary/bg' "$W/c/audit.md" && ok "component sibling pair tested" || bad "component sibling pair tested"

echo "4. Changes file"
cat > "$W/changes.json" <<'EOF'
[{"op":"rename","token":"Mapped::surface/secondary","to":"surface/brand"},
 {"op":"describe","token":"Mapped::surface/primary","description":"Default page background."},
 {"op":"set","token":"Mapped::text/link","mode":"Dark","value":"#BFDBFE"},
 {"op":"add","collection":"Mapped","name":"surface/inverse","type":"COLOR","values":{"Light":{"alias":"Alias::neutral/900"},"Dark":{"alias":"Alias::neutral/50"}}}]
EOF
python3 "$K" generate "$W/f/model.json" --changes "$W/changes.json" --infer-scopes -o "$W/ch" 2>/dev/null >/dev/null
grep -q -- '--surface-brand: var(--primary-500)' "$W/ch/tokens.css" && ok "rename applied" || bad "rename applied"
grep -q -- '--text-link: var(--secondary-200)' "$W/ch/tokens.css" && ok "raw value mapped to existing alias" || bad "raw value mapped to existing alias"
grep -q -- '--surface-inverse' "$W/ch/tokens.css" && ok "token added" || bad "token added"

echo "5. Figma apply (mocked Plugin API)"
if command -v node >/dev/null; then
  node --check "$ROOT/skills/token-push-figma/figma-plugin/code.js" && ok "code.js syntax" || bad "code.js syntax"
  node "$ROOT/tests/mock-figma.js" "$FX/figma-variables-demo.json" "$W/ch/tokens.manifest.json" "$W/exp.json" >/dev/null && ok "existing file: apply, then 0 changes" || bad "existing file: apply, then 0 changes"
  node "$ROOT/tests/mock-figma.js" - "$W/c/tokens.manifest.json" "$W/exp2.json" >/dev/null && ok "empty file: create, then 0 changes" || bad "empty file: create, then 0 changes"
  python3 "$K" ingest "$W/exp2.json" --manifest "$W/c/tokens.manifest.json" -o "$W/e/model.json" 2>/dev/null >/dev/null
  python3 "$K" generate "$W/e/model.json" -o "$W/e" 2>/dev/null >/dev/null
  diff <(grep -v 'Generated by' "$W/c/tokens.css" | sed 1,4d) <(grep -v 'Generated by' "$W/e/tokens.css" | sed 1,4d) >/dev/null && ok "Figma -> CSS identical" || bad "Figma -> CSS identical"
else
  echo "  skip node not installed"
fi

echo "6. Python/JS engine parity (Figma plugin runs the JS engine)"
if command -v node >/dev/null; then
  for x in "figma:$FX/figma-variables-demo.json" "css:$FX/tokens-demo.css" "figma:$FX/figma-rest-demo.json"; do
    k=${x%%:*}; f=${x#*:}; d="$W/par-$(basename "$f")"
    python3 "$K" ingest "$f" -o "$d/model.json" 2>/dev/null >/dev/null
    python3 "$K" audit "$d/model.json" -o "$d" 2>/dev/null >/dev/null
    python3 "$K" generate "$d/model.json" -o "$d" 2>/dev/null >/dev/null
    node "$ROOT/tests/parity.js" "$d" "$k" "$f" >/dev/null && ok "parity $(basename "$f")" || bad "parity $(basename "$f")"
  done
  python3 "$K" generate "$W/f/model.json" --changes "$W/changes.json" -o "$W/parch" 2>/dev/null >/dev/null
  cp "$W/f/audit.json" "$W/parch/"
  node "$ROOT/tests/parity.js" "$W/parch" figma "$FX/figma-variables-demo.json" "$W/changes.json" >/dev/null && ok "parity with changes" || bad "parity with changes"
  ( cd "$ROOT/skills/token-push-figma/figma-plugin" && cp code.js "$W/code.js" && cp ui.html "$W/ui.html" && bash build.sh >/dev/null )
  cmp -s "$W/code.js" "$ROOT/skills/token-push-figma/figma-plugin/code.js" && cmp -s "$W/ui.html" "$ROOT/skills/token-push-figma/figma-plugin/ui.html" && ok "built plugin files are up to date" || bad "built plugin files are up to date (run build.sh)"
fi

echo "7. Figma plugin UI end to end (headless Chromium)"
if node -e "require('playwright')" 2>/dev/null; then
  node "$ROOT/tests/e2e-plugin.js" > "$W/e2e.log" 2>&1 && ok "plugin: scan, audit, fix, preview, apply, rescan, export, import" || { bad "plugin e2e"; cat "$W/e2e.log"; }
else
  echo "  skip playwright not installed (npm i playwright)"
fi

echo
echo "$pass passed, $fail failed"
[ "$fail" -eq 0 ]
