#!/usr/bin/env bash
# Builds the Figma plugin files from sources:
#   code.js = core.js + shell.js
#   ui.html = ui.src.html with engine.js inlined
set -euo pipefail
cd "$(dirname "$0")"
{ echo "// GENERATED by build.sh from core.js + shell.js. Do not edit."; cat core.js shell.js; } > code.js
python3 - <<'PY'
src = open("ui.src.html", encoding="utf-8").read()
eng = open("engine.js", encoding="utf-8").read()
out = src.replace("<!-- Source of ui.html. Build with: bash build.sh (inlines engine.js). -->", "<!-- GENERATED by build.sh from ui.src.html + engine.js. Do not edit. -->")
out = out.replace("/*__ENGINE__*/", eng)
open("ui.html", "w", encoding="utf-8").write(out)
PY
echo "built code.js and ui.html"
