// GENERATED by build.sh from core.js + shell.js. Do not edit.
// token-foundry core (Figma Plugin API). Shared by the Figma plugin (code.js) and
// the MCP route (use_figma). No network, no deletes. Idempotent: a second apply of
// the same manifest reports 0 changes.
//
//   await tfExport()                       -> figma-export@1 JSON (IDs, modes, aliases, scopes, code syntax)
//   await tfApply(manifest, { dryRun })    -> report (simulation when dryRun !== false)

const TF_VERSION = "0.2.0";

function tfHexToRgb(hex) {
  let h = String(hex).trim().replace(/^#/, "");
  if (h.length === 3 || h.length === 4) h = h.split("").map((c) => c + c).join("");
  if (!/^[0-9a-fA-F]{6}([0-9a-fA-F]{2})?$/.test(h)) throw new Error("Invalid color " + hex);
  const n = (i) => parseInt(h.slice(i, i + 2), 16) / 255;
  return { r: n(0), g: n(2), b: n(4), a: h.length === 8 ? n(6) : 1 };
}

function tfToFigmaValue(type, value) {
  if (type === "COLOR") return tfHexToRgb(value);
  if (type === "FLOAT") return Number(value);
  if (type === "BOOLEAN") return Boolean(value);
  return String(value);
}

function tfSame(cur, want) {
  if (cur === undefined || cur === null) return false;
  if (want && want.type === "VARIABLE_ALIAS") return !!cur && cur.type === "VARIABLE_ALIAS" && cur.id === want.id;
  if (cur && cur.type === "VARIABLE_ALIAS") return false;
  if (typeof want === "object") {
    const tol = 0.5 / 255;
    return ["r", "g", "b"].every((k) => Math.abs(cur[k] - want[k]) <= tol) && Math.abs((cur.a === undefined ? 1 : cur.a) - want.a) <= tol;
  }
  if (typeof want === "number") return Math.abs(cur - want) < 1e-6;
  return cur === want;
}

function tfSameArr(a, b) {
  a = (a || []).slice().sort();
  b = (b || []).slice().sort();
  return a.length === b.length && a.every((x, i) => x === b[i]);
}

async function tfExport() {
  const cols = await figma.variables.getLocalVariableCollectionsAsync();
  const vars = await figma.variables.getLocalVariablesAsync();
  return {
    format: "token-foundry/figma-export@1",
    version: TF_VERSION,
    fileName: figma.root.name,
    exportedAt: new Date().toISOString(),
    collections: cols.map((c) => ({
      id: c.id, name: c.name, defaultModeId: c.defaultModeId, remote: c.remote,
      modes: c.modes.map((m) => ({ modeId: m.modeId, name: m.name })),
      variableIds: c.variableIds,
    })),
    variables: vars.map((v) => ({
      id: v.id, name: v.name, resolvedType: v.resolvedType, variableCollectionId: v.variableCollectionId,
      valuesByMode: v.valuesByMode, scopes: v.scopes, description: v.description,
      codeSyntax: v.codeSyntax, hiddenFromPublishing: v.hiddenFromPublishing,
    })),
  };
}

async function tfApply(manifest, opts) {
  opts = Object.assign({ dryRun: true, scopes: true, codeSyntax: true, descriptions: true, only: null }, opts || {});
  const dry = opts.dryRun !== false;
  if (!manifest || !/^token-foundry\/manifest@/.test(manifest.format || "")) {
    throw new Error("Not a token-foundry manifest (expected format token-foundry/manifest@1)");
  }
  const R = {
    dryRun: dry, version: TF_VERSION,
    created: { collections: [], modes: [], variables: [] },
    renamed: [], updated: [], unchanged: 0, errors: [], warnings: [], leftovers: [], safety: null, idMap: {},
  };
  const cols = await figma.variables.getLocalVariableCollectionsAsync();
  const vars = await figma.variables.getLocalVariablesAsync();
  const colById = new Map(cols.map((c) => [c.id, c]));
  const colByName = new Map(cols.map((c) => [c.name, c]));
  const varById = new Map(vars.map((v) => [v.id, v]));
  const varByKey = new Map(vars.map((v) => [v.variableCollectionId + "::" + v.name, v]));

  // 1. Collections and modes
  const onlyCols = opts.only ? new Set(opts.only) : null;
  const colCtx = new Map();
  for (const mc of manifest.collections) {
    let col = (mc.figmaId && colById.get(mc.figmaId)) || colByName.get(mc.name) || null;
    let isNew = false;
    if (col && col.name !== mc.name) {
      R.renamed.push({ collection: col.name, to: mc.name });
      if (!dry) col.name = mc.name;
    }
    if (!col) {
      isNew = true;
      R.created.collections.push(mc.name);
      if (!dry) col = figma.variables.createVariableCollection(mc.name);
    }
    const modeIds = {};
    mc.modes.forEach((mm, i) => {
      if (!col) {
        if (i > 0) R.created.modes.push(mc.name + " / " + mm.name);
        modeIds[mm.name] = "pending";
        return;
      }
      let m = col.modes.find((x) => mm.figmaId && x.modeId === mm.figmaId) || col.modes.find((x) => x.name === mm.name);
      if (!m && i === 0 && isNew) {
        col.renameMode(col.modes[0].modeId, mm.name);
        m = { modeId: col.modes[0].modeId, name: mm.name };
      } else if (m && m.name !== mm.name) {
        R.renamed.push({ collection: mc.name, mode: m.name, to: mm.name });
        if (!dry) col.renameMode(m.modeId, mm.name);
      }
      if (!m) {
        R.created.modes.push(mc.name + " / " + mm.name);
        if (!dry) {
          try { m = { modeId: col.addMode(mm.name), name: mm.name }; }
          catch (e) { R.errors.push("Cannot add mode '" + mm.name + "' to " + mc.name + ": " + e.message + " (plan mode limit?)"); }
        } else {
          modeIds[mm.name] = "pending";
          return;
        }
      }
      if (m) modeIds[mm.name] = m.modeId;
    });
    colCtx.set(mc.name, { col, modeIds, skip: onlyCols && !onlyCols.has(mc.name) });
  }

  // 2. Variables (match by Figma ID, then collection + name)
  const tokCtx = new Map();
  const pending = new Set();
  for (const t of manifest.tokens) {
    const key = t.collection + "::" + t.name;
    const cc = colCtx.get(t.collection);
    if (!cc) { R.errors.push(key + ": collection missing from manifest"); continue; }
    let v = (t.figmaId && varById.get(t.figmaId)) || null;
    if (v && cc.col && v.variableCollectionId !== cc.col.id) {
      R.warnings.push(key + ": Figma ID belongs to another collection, matched by name instead");
      v = null;
    }
    if (!v && cc.col) v = varByKey.get(cc.col.id + "::" + t.name) || null;
    if (v && v.resolvedType !== t.type) {
      R.errors.push(key + ": type " + v.resolvedType + " in Figma vs " + t.type + " in manifest, skipped");
      tokCtx.set(key, { skip: true });
      continue;
    }
    if (cc.skip) { tokCtx.set(key, { v, t, cc, skipWrite: true }); if (v) R.idMap[key] = v.id; continue; }
    if (v && v.name !== t.name) {
      R.renamed.push({ variable: v.name, to: t.name, collection: t.collection });
      if (!dry) v.name = t.name;
    }
    if (!v) {
      R.created.variables.push(key);
      if (!dry && cc.col) v = figma.variables.createVariable(t.name, cc.col, t.type);
      else pending.add(key);
    }
    tokCtx.set(key, { v, t, cc });
    if (v) R.idMap[key] = v.id;
  }

  // 3. Values and metadata
  for (const [key, ctx] of tokCtx) {
    if (ctx.skip || ctx.skipWrite) continue;
    const { v, t, cc } = ctx;
    const modes = [];
    const meta = [];
    for (const [modeName, val] of Object.entries(t.values || {})) {
      const modeId = cc.modeIds[modeName];
      if (!modeId) { R.errors.push(key + ": mode '" + modeName + "' not in collection"); continue; }
      let want;
      if (val.alias) {
        const a = val.alias;
        if (a.external) { R.warnings.push(key + " [" + modeName + "]: external alias left untouched"); continue; }
        const tkey = a.collection + "::" + a.name;
        const tctx = tokCtx.get(tkey);
        let target = (tctx && tctx.v) || (a.figmaId && varById.get(a.figmaId)) || null;
        if (!target) {
          if (pending.has(tkey)) { modes.push(modeName); continue; } // created on apply
          R.errors.push(key + " [" + modeName + "]: alias target " + tkey + " not found");
          continue;
        }
        want = { type: "VARIABLE_ALIAS", id: target.id };
      } else {
        try { want = tfToFigmaValue(t.type, val.value); }
        catch (e) { R.errors.push(key + " [" + modeName + "]: " + e.message); continue; }
      }
      if (!v || modeId === "pending") { modes.push(modeName); continue; }
      if (tfSame(v.valuesByMode[modeId], want)) continue;
      modes.push(modeName);
      if (!dry) {
        try { v.setValueForMode(modeId, want); }
        catch (e) { R.errors.push(key + " [" + modeName + "]: " + e.message); }
      }
    }
    if (opts.descriptions && t.description && (!v || v.description !== t.description)) {
      meta.push("description");
      if (!dry && v) v.description = t.description;
    }
    const web = t.codeSyntax && t.codeSyntax.WEB;
    if (opts.codeSyntax && web && (!v || (v.codeSyntax || {}).WEB !== web)) {
      meta.push("codeSyntax");
      if (!dry && v) v.setVariableCodeSyntax("WEB", web);
    }
    if (opts.scopes && Array.isArray(t.scopes) && (!v || !tfSameArr(v.scopes, t.scopes))) {
      meta.push("scopes");
      if (!dry && v) {
        try { v.scopes = t.scopes; } catch (e) { R.warnings.push(key + ": scopes " + JSON.stringify(t.scopes) + " rejected: " + e.message); }
      }
    }
    if (modes.length || meta.length) R.updated.push({ token: key, modes, meta });
    else R.unchanged++;
  }

  // 4. Leftovers: reported, never deleted
  const manifestKeys = new Set(manifest.tokens.map((t) => t.collection + "::" + t.name));
  for (const v of vars) {
    const col = colById.get(v.variableCollectionId);
    if (col && colCtx.has(col.name) && !manifestKeys.has(col.name + "::" + v.name) &&
        !R.renamed.some((r) => r.variable === v.name)) R.leftovers.push(col.name + "::" + v.name);
  }

  // 5. Safety net: re-read every written variable and check each mode resolves
  if (!dry) {
    const problems = [];
    const entries = [...tokCtx.entries()].filter(([, c]) => c.v && !c.skip);
    const fresh = await Promise.all(entries.map(([, c]) => figma.variables.getVariableByIdAsync(c.v.id)));
    const freshCols = await figma.variables.getLocalVariableCollectionsAsync();
    const colModes = new Map(freshCols.map((c) => [c.id, c.modes]));
    const aliasIds = new Set();
    fresh.forEach((fv, i) => {
      if (!fv) { problems.push(entries[i][0] + ": missing after apply"); return; }
      for (const m of colModes.get(fv.variableCollectionId) || []) {
        const val = fv.valuesByMode[m.modeId];
        if (val === undefined || val === null) problems.push(entries[i][0] + " [" + m.name + "]: no value");
        else if (val.type === "VARIABLE_ALIAS") aliasIds.add(val.id);
      }
    });
    const targets = await Promise.all([...aliasIds].map((id) => figma.variables.getVariableByIdAsync(id)));
    [...aliasIds].forEach((id, i) => { if (!targets[i]) problems.push("alias target " + id + " does not resolve"); });
    R.safety = { checked: fresh.length, problems };
  }

  const cap = (a) => (a.length > 300 ? a.slice(0, 300).concat(["... " + (a.length - 300) + " more"]) : a);
  R.summary = {
    createdCollections: R.created.collections.length, createdModes: R.created.modes.length,
    createdVariables: R.created.variables.length, renamed: R.renamed.length, updated: R.updated.length,
    unchanged: R.unchanged, leftovers: R.leftovers.length, errors: R.errors.length, warnings: R.warnings.length,
    totalChanges: R.created.collections.length + R.created.modes.length + R.created.variables.length + R.renamed.length + R.updated.length,
  };
  R.updated = cap(R.updated);
  R.leftovers = cap(R.leftovers);
  R.created.variables = cap(R.created.variables);
  return R;
}

// ---- Figma plugin shell ----------------------------------------------------
// The UI (ui.html) runs the audit engine; this side only reads and writes variables.
figma.showUI(__html__, { width: 600, height: 760, themeColors: true });

figma.ui.onmessage = async (msg) => {
  try {
    if (msg.type === "scan") {
      const data = await tfExport();
      figma.ui.postMessage({ type: "scan", data, afterApply: !!msg.afterApply });
    } else if (msg.type === "apply") {
      const report = await tfApply(msg.manifest, msg.options);
      figma.ui.postMessage({ type: "report", report });
      if (!report.dryRun) figma.notify("Token Foundry: " + report.summary.totalChanges + " changes applied" + (report.summary.errors ? ", " + report.summary.errors + " errors" : ""));
    } else if (msg.type === "close") {
      figma.closePlugin();
    }
  } catch (e) {
    figma.ui.postMessage({ type: "error", message: String((e && e.message) || e) });
  }
};
